### ISSUE TITLE
The map isnt fluid, you can see the endges of triangles

### ISSUE THREAD

**Issue by oskaddddd** [oskaddddd/Visualizing-Geographical-Data#2]

**Comment by MegaLime0** [comment]
i can see them from all the way over here

**Comment by oskaddddd** [comment]
-_-, Ill make a quick solution in like 2 weeks, but the points will have to be in a grid

**Comment by oskaddddd** [comment]
Intended behavior. Tho I'll try to make a new interpolation mode which is more fluid tho less accurate.
