### ISSUE TITLE
Repository contains unnecessary data

### ISSUE THREAD

**Issue by MegaLime0** [oskaddddd/Visualizing-Geographical-Data#4]
The repository contains unnecessary folders like ".vscode" and "\_\_pycache\_\_" which add a significant amount to the overall size. This makes cloning the repo take longer.

**Comment by MegaLime0** [comment]
Should be as easy as removing the folders from the repo and adding them to the gitignore file

**Comment by oskaddddd** [comment]
Thanks a lot for help resolving this.
